### ISSUE TITLE
Database creation

### ISSUE THREAD

**Issue by RenanStigliani** [leolana/LogToday#2]
Hi, I just cloned the project but when I run it (in VS2013, pressing F5) it keeps telling that the Database 'LogToday' does not exists. I have Sql Server installed, but I could not find any scripts to create the Database, how do I create it?

**Comment by leolana** [comment]
Sorry for the delay in answering you. In the last commit I made, configured one local database that is in App_Data folder, just configure the web.config to atach it and will probably be resolved. I also configured the web.config with this change. Right?
